id: I583AD2C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:44:42+00:00'
last_modified: '2022-06-07T13:59:06.134676+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD100944
  title: སྔ་འགྱུར་བཀའ་མ་ཤིན་ཏུ་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A89F:
      image_group_id: I1PD106519
      title: ''
      total_pages: 980
      order: 1
      base_file: A89F.txt
    A7A4:
      image_group_id: I1PD106520
      title: ''
      total_pages: 706
      order: 2
      base_file: A7A4.txt
    '1201':
      image_group_id: I1PD106521
      title: ''
      total_pages: 816
      order: 3
      base_file: 1201.txt
    93E3:
      image_group_id: I1PD106522
      title: ''
      total_pages: 694
      order: 4
      base_file: 93E3.txt
    '2006':
      image_group_id: I1PD106523
      title: ''
      total_pages: 760
      order: 5
      base_file: 2006.txt
    D260:
      image_group_id: I1PD106524
      title: ''
      total_pages: 934
      order: 6
      base_file: D260.txt
    075F:
      image_group_id: I1PD106525
      title: ''
      total_pages: 560
      order: 7
      base_file: 075F.txt
    10BB:
      image_group_id: I1PD106526
      title: ''
      total_pages: 612
      order: 8
      base_file: 10BB.txt
    A499:
      image_group_id: I1PD106527
      title: ''
      total_pages: 660
      order: 9
      base_file: A499.txt
    02C0:
      image_group_id: I1PD106528
      title: ''
      total_pages: 802
      order: 10
      base_file: 02C0.txt
    DF42:
      image_group_id: I1PD106529
      title: ''
      total_pages: 680
      order: 11
      base_file: DF42.txt
    696E:
      image_group_id: I1PD106530
      title: ''
      total_pages: 600
      order: 12
      base_file: 696E.txt
    54F2:
      image_group_id: I1PD106531
      title: ''
      total_pages: 876
      order: 13
      base_file: 54F2.txt
    '6248':
      image_group_id: I1PD106532
      title: ''
      total_pages: 744
      order: 14
      base_file: 6248.txt
    9ADE:
      image_group_id: I1PD106533
      title: ''
      total_pages: 766
      order: 15
      base_file: 9ADE.txt
    C9CA:
      image_group_id: I1PD106534
      title: ''
      total_pages: 752
      order: 16
      base_file: C9CA.txt
    C9EC:
      image_group_id: I1PD106535
      title: ''
      total_pages: 780
      order: 17
      base_file: C9EC.txt
    505E:
      image_group_id: I1PD106536
      title: ''
      total_pages: 692
      order: 18
      base_file: 505E.txt
    FCB7:
      image_group_id: I1PD106537
      title: ''
      total_pages: 692
      order: 19
      base_file: FCB7.txt
    33EF:
      image_group_id: I1PD106538
      title: ''
      total_pages: 614
      order: 20
      base_file: 33EF.txt
    CAFC:
      image_group_id: I1PD106539
      title: ''
      total_pages: 638
      order: 21
      base_file: CAFC.txt
    0F16:
      image_group_id: I1PD106540
      title: ''
      total_pages: 652
      order: 22
      base_file: 0F16.txt
    08D2:
      image_group_id: I1PD106541
      title: ''
      total_pages: 612
      order: 23
      base_file: 08D2.txt
    4B22:
      image_group_id: I1PD106542
      title: ''
      total_pages: 892
      order: 24
      base_file: 4B22.txt
    28CC:
      image_group_id: I1PD106543
      title: ''
      total_pages: 636
      order: 25
      base_file: 28CC.txt
    DA00:
      image_group_id: I1PD106544
      title: ''
      total_pages: 660
      order: 26
      base_file: DA00.txt
    C393:
      image_group_id: I1PD106545
      title: ''
      total_pages: 754
      order: 27
      base_file: C393.txt
    '1878':
      image_group_id: I1PD106546
      title: ''
      total_pages: 604
      order: 28
      base_file: 1878.txt
    E712:
      image_group_id: I1PD106547
      title: ''
      total_pages: 572
      order: 29
      base_file: E712.txt
    DF17:
      image_group_id: I1PD106548
      title: ''
      total_pages: 716
      order: 30
      base_file: DF17.txt
    0930:
      image_group_id: I1PD106549
      title: ''
      total_pages: 860
      order: 31
      base_file: 0930.txt
    D9C7:
      image_group_id: I1PD106550
      title: ''
      total_pages: 612
      order: 32
      base_file: D9C7.txt
    '5304':
      image_group_id: I1PD106551
      title: ''
      total_pages: 840
      order: 33
      base_file: 5304.txt
    68AD:
      image_group_id: I1PD106552
      title: ''
      total_pages: 716
      order: 34
      base_file: 68AD.txt
    2B68:
      image_group_id: I1PD106553
      title: ''
      total_pages: 668
      order: 35
      base_file: 2B68.txt
    '2265':
      image_group_id: I1PD106554
      title: ''
      total_pages: 630
      order: 36
      base_file: 2265.txt
    440E:
      image_group_id: I1PD106555
      title: ''
      total_pages: 376
      order: 37
      base_file: 440E.txt
    594C:
      image_group_id: I1PD106556
      title: ''
      total_pages: 540
      order: 38
      base_file: 594C.txt
    EFE4:
      image_group_id: I1PD106557
      title: ''
      total_pages: 536
      order: 39
      base_file: EFE4.txt
    0D87:
      image_group_id: I1PD106558
      title: ''
      total_pages: 814
      order: 40
      base_file: 0D87.txt
    '0350':
      image_group_id: I1PD106559
      title: ''
      total_pages: 932
      order: 41
      base_file: 0350.txt
    D0EF:
      image_group_id: I1PD106560
      title: ''
      total_pages: 690
      order: 42
      base_file: D0EF.txt
    F368:
      image_group_id: I1PD106561
      title: ''
      total_pages: 684
      order: 43
      base_file: F368.txt
    1D0B:
      image_group_id: I1PD106562
      title: ''
      total_pages: 644
      order: 44
      base_file: 1D0B.txt
    B555:
      image_group_id: I1PD106563
      title: ''
      total_pages: 644
      order: 45
      base_file: B555.txt
    316F:
      image_group_id: I1PD106564
      title: ''
      total_pages: 1160
      order: 46
      base_file: 316F.txt
    9C08:
      image_group_id: I1PD106565
      title: ''
      total_pages: 622
      order: 47
      base_file: 9C08.txt
    A5EB:
      image_group_id: I1PD106566
      title: ''
      total_pages: 596
      order: 48
      base_file: A5EB.txt
    453C:
      image_group_id: I1PD106567
      title: ''
      total_pages: 560
      order: 49
      base_file: 453C.txt
    11B9:
      image_group_id: I1PD106568
      title: ''
      total_pages: 614
      order: 50
      base_file: 11B9.txt
    80E3:
      image_group_id: I1PD106569
      title: ''
      total_pages: 636
      order: 51
      base_file: 80E3.txt
    7BCB:
      image_group_id: I1PD106570
      title: ''
      total_pages: 588
      order: 52
      base_file: 7BCB.txt
    EC0C:
      image_group_id: I1PD106571
      title: ''
      total_pages: 626
      order: 53
      base_file: EC0C.txt
    F350:
      image_group_id: I1PD106572
      title: ''
      total_pages: 608
      order: 54
      base_file: F350.txt
    1C33:
      image_group_id: I1PD106573
      title: ''
      total_pages: 592
      order: 55
      base_file: 1C33.txt
    '9567':
      image_group_id: I1PD106574
      title: ''
      total_pages: 524
      order: 56
      base_file: 9567.txt
    2E44:
      image_group_id: I1PD106575
      title: ''
      total_pages: 460
      order: 57
      base_file: 2E44.txt
    E7BA:
      image_group_id: I1PD106576
      title: ''
      total_pages: 768
      order: 58
      base_file: E7BA.txt
    B4B6:
      image_group_id: I1PD106577
      title: ''
      total_pages: 500
      order: 59
      base_file: B4B6.txt
    B539:
      image_group_id: I1PD106578
      title: ''
      total_pages: 784
      order: 60
      base_file: B539.txt
    2DEB:
      image_group_id: I1PD106579
      title: ''
      total_pages: 530
      order: 61
      base_file: 2DEB.txt
    '9489':
      image_group_id: I1PD106580
      title: ''
      total_pages: 546
      order: 62
      base_file: 9489.txt
    F8A8:
      image_group_id: I1PD106581
      title: ''
      total_pages: 730
      order: 63
      base_file: F8A8.txt
    '3030':
      image_group_id: I1PD106582
      title: ''
      total_pages: 772
      order: 64
      base_file: 3030.txt
    '7437':
      image_group_id: I1PD106583
      title: ''
      total_pages: 484
      order: 65
      base_file: 7437.txt
    BFBA:
      image_group_id: I1PD106584
      title: ''
      total_pages: 530
      order: 66
      base_file: BFBA.txt
    6EC1:
      image_group_id: I1PD106585
      title: ''
      total_pages: 620
      order: 67
      base_file: 6EC1.txt
    D11B:
      image_group_id: I1PD106586
      title: ''
      total_pages: 652
      order: 68
      base_file: D11B.txt
    CCCE:
      image_group_id: I1PD106587
      title: ''
      total_pages: 676
      order: 69
      base_file: CCCE.txt
    B969:
      image_group_id: I1PD106588
      title: ''
      total_pages: 404
      order: 70
      base_file: B969.txt
    '8289':
      image_group_id: I1PD106589
      title: ''
      total_pages: 708
      order: 71
      base_file: 8289.txt
    CA17:
      image_group_id: I1PD106590
      title: ''
      total_pages: 634
      order: 72
      base_file: CA17.txt
    945D:
      image_group_id: I1PD106591
      title: ''
      total_pages: 756
      order: 73
      base_file: 945D.txt
    7BFD:
      image_group_id: I1PD106592
      title: ''
      total_pages: 730
      order: 74
      base_file: 7BFD.txt
    87D7:
      image_group_id: I1PD106593
      title: ''
      total_pages: 692
      order: 75
      base_file: 87D7.txt
    3C13:
      image_group_id: I1PD106594
      title: ''
      total_pages: 748
      order: 76
      base_file: 3C13.txt
    D043:
      image_group_id: I1PD106595
      title: ''
      total_pages: 860
      order: 77
      base_file: D043.txt
    8F17:
      image_group_id: I1PD106596
      title: ''
      total_pages: 804
      order: 78
      base_file: 8F17.txt
    '4839':
      image_group_id: I1PD106597
      title: ''
      total_pages: 572
      order: 79
      base_file: 4839.txt
    '3711':
      image_group_id: I1PD106598
      title: ''
      total_pages: 674
      order: 80
      base_file: 3711.txt
    B78E:
      image_group_id: I1PD106599
      title: ''
      total_pages: 564
      order: 81
      base_file: B78E.txt
    FBDF:
      image_group_id: I1PD106600
      title: ''
      total_pages: 476
      order: 82
      base_file: FBDF.txt
    '7342':
      image_group_id: I1PD106601
      title: ''
      total_pages: 468
      order: 83
      base_file: 7342.txt
    '5520':
      image_group_id: I1PD106602
      title: ''
      total_pages: 536
      order: 84
      base_file: 5520.txt
    B8E0:
      image_group_id: I1PD106603
      title: ''
      total_pages: 656
      order: 85
      base_file: B8E0.txt
    A3A3:
      image_group_id: I1PD106604
      title: ''
      total_pages: 700
      order: 86
      base_file: A3A3.txt
    2AFE:
      image_group_id: I1PD106605
      title: ''
      total_pages: 462
      order: 87
      base_file: 2AFE.txt
    C8C8:
      image_group_id: I1PD106606
      title: ''
      total_pages: 668
      order: 88
      base_file: C8C8.txt
    59AB:
      image_group_id: I1PD106607
      title: ''
      total_pages: 658
      order: 89
      base_file: 59AB.txt
    F7EA:
      image_group_id: I1PD106608
      title: ''
      total_pages: 466
      order: 90
      base_file: F7EA.txt
    29D4:
      image_group_id: I1PD106609
      title: ''
      total_pages: 850
      order: 91
      base_file: 29D4.txt
    75C6:
      image_group_id: I1PD106610
      title: ''
      total_pages: 780
      order: 92
      base_file: 75C6.txt
    '6580':
      image_group_id: I1PD106611
      title: ''
      total_pages: 778
      order: 93
      base_file: 6580.txt
    C88E:
      image_group_id: I1PD106612
      title: ''
      total_pages: 714
      order: 94
      base_file: C88E.txt
    81AA:
      image_group_id: I1PD106613
      title: ''
      total_pages: 640
      order: 95
      base_file: 81AA.txt
    57CE:
      image_group_id: I1PD106614
      title: ''
      total_pages: 690
      order: 96
      base_file: 57CE.txt
    '3925':
      image_group_id: I1PD106615
      title: ''
      total_pages: 422
      order: 97
      base_file: 3925.txt
    B4EE:
      image_group_id: I1PD106616
      title: ''
      total_pages: 558
      order: 98
      base_file: B4EE.txt
    09AA:
      image_group_id: I1PD106617
      title: ''
      total_pages: 458
      order: 99
      base_file: 09AA.txt
    014C:
      image_group_id: I1PD106618
      title: ''
      total_pages: 418
      order: 100
      base_file: 014C.txt
    F0CA:
      image_group_id: I1PD106619
      title: ''
      total_pages: 652
      order: 101
      base_file: F0CA.txt
    E8D3:
      image_group_id: I1PD106620
      title: ''
      total_pages: 556
      order: 102
      base_file: E8D3.txt
    9AA4:
      image_group_id: I1PD106621
      title: ''
      total_pages: 848
      order: 103
      base_file: 9AA4.txt
    454B:
      image_group_id: I1PD106622
      title: ''
      total_pages: 740
      order: 104
      base_file: 454B.txt
    F5D0:
      image_group_id: I1PD106623
      title: ''
      total_pages: 980
      order: 105
      base_file: F5D0.txt
    AC7A:
      image_group_id: I1PD106624
      title: ''
      total_pages: 1028
      order: 106
      base_file: AC7A.txt
    88C4:
      image_group_id: I1PD106625
      title: ''
      total_pages: 592
      order: 107
      base_file: 88C4.txt
    '6223':
      image_group_id: I1PD106626
      title: ''
      total_pages: 692
      order: 108
      base_file: 6223.txt
    FC87:
      image_group_id: I1PD106627
      title: ''
      total_pages: 684
      order: 109
      base_file: FC87.txt
    '0241':
      image_group_id: I1PD106628
      title: ''
      total_pages: 588
      order: 110
      base_file: 0241.txt
    6E6F:
      image_group_id: I1PD106629
      title: ''
      total_pages: 672
      order: 111
      base_file: 6E6F.txt
    E699:
      image_group_id: I1PD106630
      title: ''
      total_pages: 664
      order: 112
      base_file: E699.txt
    40ED:
      image_group_id: I1PD106631
      title: ''
      total_pages: 628
      order: 113
      base_file: 40ED.txt
    507E:
      image_group_id: I1PD106632
      title: ''
      total_pages: 652
      order: 114
      base_file: 507E.txt
    B3EF:
      image_group_id: I1PD106633
      title: ''
      total_pages: 914
      order: 115
      base_file: B3EF.txt
    D6CD:
      image_group_id: I1PD106634
      title: ''
      total_pages: 1438
      order: 116
      base_file: D6CD.txt
    EAE2:
      image_group_id: I1PD106635
      title: ''
      total_pages: 602
      order: 117
      base_file: EAE2.txt
    903F:
      image_group_id: I1PD106636
      title: ''
      total_pages: 724
      order: 118
      base_file: 903F.txt
    AECE:
      image_group_id: I1PD106637
      title: ''
      total_pages: 450
      order: 119
      base_file: AECE.txt
    0DD8:
      image_group_id: I1PD106638
      title: ''
      total_pages: 480
      order: 120
      base_file: 0DD8.txt
    617B:
      image_group_id: I1PD106639
      title: ''
      total_pages: 640
      order: 121
      base_file: 617B.txt
    EF44:
      image_group_id: I1PD106640
      title: ''
      total_pages: 524
      order: 122
      base_file: EF44.txt
    '6070':
      image_group_id: I1PD106641
      title: ''
      total_pages: 432
      order: 123
      base_file: 6070.txt
    E0F4:
      image_group_id: I1PD106642
      title: ''
      total_pages: 628
      order: 124
      base_file: E0F4.txt
    99E1:
      image_group_id: I1PD106643
      title: ''
      total_pages: 380
      order: 125
      base_file: 99E1.txt
    '6687':
      image_group_id: I1PD106644
      title: ''
      total_pages: 506
      order: 126
      base_file: 6687.txt
    B040:
      image_group_id: I1PD106645
      title: ''
      total_pages: 564
      order: 127
      base_file: B040.txt
    '1155':
      image_group_id: I1PD106646
      title: ''
      total_pages: 544
      order: 128
      base_file: 1155.txt
    '8803':
      image_group_id: I1PD106647
      title: ''
      total_pages: 466
      order: 129
      base_file: 8803.txt
    0ADE:
      image_group_id: I1PD106648
      title: ''
      total_pages: 444
      order: 130
      base_file: 0ADE.txt
    DFE4:
      image_group_id: I1PD106649
      title: ''
      total_pages: 612
      order: 131
      base_file: DFE4.txt
    '7091':
      image_group_id: I1PD106650
      title: ''
      total_pages: 616
      order: 132
      base_file: 7091.txt
    C8AF:
      image_group_id: I1PD106651
      title: ''
      total_pages: 694
      order: 133
      base_file: C8AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
